#!/bin/sh

SCRIPT_FILE=$0
HOST=${1-192.168.99.100}
BUCKET=${2-cmbucket}
PASSWORD=${3-cmpasswd}

TARGET_FILE=$0

cd $(dirname $TARGET_FILE)
TARGET_FILE=$(basename $TARGET_FILE)
while [ -L "$TARGET_FILE" ]
do
    TARGET_FILE=$(readlink $TARGET_FILE)
    cd $(dirname $TARGET_FILE)
    TARGET_FILE=$(basename $TARGET_FILE)
done

# Compute the canonicalized name by finding the physical path 
# for the directory we're in and appending the target file.
PHYS_DIR=$(pwd -P)
RESULT=$PHYS_DIR/$TARGET_FILE

cd $(dirname $RESULT)
java -Dhost=$HOST \
     -Dbucket=${BUCKET} \
     -Dpassword=${PASSWORD} \
     -Djava.util.logging.config.file=../logging.properties \
     -jar ../cbtail.jar
